secrets:
  discord_token: ""
  wolfram_alpha_appid: ""
  open_weather_appid: ""
  bing:
    clientid: ""
    secret: ""
  osu_api_key: ""

  db:
    dbname: "lemon"
    username: "lemon"
    password: "lemon"

  redis:
    port: 6379
    bind: 127.0.0.1
